<?php

namespace App\Services;

use App\Models\Flat;
use App\Models\FlatTenant;
use App\Models\MonthlyBill;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class AutoBillGenerator
{
    /**
     * The rent fields to copy from the flat to the bill.
     */
    private static array $rentFields = [
        'house_rent', 'wasa', 'common_electricity', 'gas',
        'utility', 'parking', 'society_bill', 'security', 'other',
    ];

    /**
     * Main entry point. Call this on login to auto-generate any missing bills.
     * Logic: For each active, occupied flat — check if the current month's bill
     * already exists. If not, and if the tenant's start_date is in a previous
     * month (or same month), generate the bill automatically.
     *
     * @param int|null $userId  If provided, only generates bills for flats
     *                          belonging to this admin's buildings.
     */
    public static function generateForUser(?int $userId = null): void
    {
        try {
            $currentMonth = now()->format('Y-m');
            $today        = now();

            // Fetch all active+occupied flats with their active tenant and building
            $query = Flat::with(['activeTenant', 'building'])
                ->where('bill_status', 'active')
                ->where('status', 'occupied'); // booked_by_owner flats are intentionally excluded

            // If a specific admin user, scope to their buildings only
            if ($userId !== null) {
                $query->whereHas('building', fn($q) => $q->where('user_id', $userId));
            }

            $flats = $query->get();

            foreach ($flats as $flat) {
                self::maybeGenerateBill($flat, $currentMonth, $today);
            }
        } catch (\Throwable $e) {
            // Log silently — never break the login flow
            Log::error('AutoBillGenerator error: ' . $e->getMessage(), [
                'trace' => $e->getTraceAsString(),
            ]);
        }
    }

    /**
     * Check and generate a bill for a single flat if needed.
     */
    private static function maybeGenerateBill(Flat $flat, string $currentMonth, Carbon $today): void
    {
        $activeFlatTenant = $flat->activeTenant;

        // No active tenant → skip
        if (!$activeFlatTenant) {
            return;
        }

        $startDate = $activeFlatTenant->start_date;

        // Tenant started this month and today is not the 1st → skip
        // We only generate bills for months that have fully started
        // i.e., the tenant's start_date month is before or equal to current month
        if ($startDate === null) {
            return;
        }

        $startMonth = $startDate->format('Y-m');

        // Only generate if the tenant started in a month that is <= current month
        if ($startMonth > $currentMonth) {
            return;
        }

        // Bill for this month already exists? → skip (prevents duplicates with manual)
        $alreadyExists = MonthlyBill::where('flat_id', $flat->id)
            ->where('bill_month', $currentMonth)
            ->exists();

        if ($alreadyExists) {
            return;
        }

        // Calculate previous_due from the last bill's remaining_amount
        $lastBill    = MonthlyBill::where('flat_id', $flat->id)
            ->latest('id')
            ->first();
        $previousDue = $lastBill ? (float) $lastBill->remaining_amount : 0;

        // Build rent breakdown from the flat's stored values
        $breakdown = [];
        $total     = 0;
        foreach (self::$rentFields as $field) {
            $breakdown[$field] = (float) ($flat->$field ?? 0);
            $total            += $breakdown[$field];
        }

        [$year, $month] = explode('-', $currentMonth);

        DB::beginTransaction();
        try {
            MonthlyBill::create(array_merge($breakdown, [
                'flat_id'           => $flat->id,
                'building_id'       => $flat->building_id,
                'tenant_id'         => $activeFlatTenant->tenant_id,
                'flat_tenant_id'    => $activeFlatTenant->id,
                'bill_month'        => $currentMonth,
                'bill_year'         => (int) $year,
                'bill_month_number' => (int) $month,
                'total_amount'      => $total,
                'paid_amount'       => 0,
                'remaining_amount'  => $total + $previousDue,
                'previous_due'      => $previousDue,
                'collection_status' => 'due',
                'notes'             => 'Auto-generated by system.',
                'generated_by'      => null, // system-generated, no user
            ]));

            DB::commit();
        } catch (\Throwable $e) {
            DB::rollBack();
            Log::error("AutoBillGenerator: Failed for flat #{$flat->id} – " . $e->getMessage());
        }
    }
}
