<?php

use App\Models\Building;
use App\Models\Flat;
use App\Models\FlatTenant;
use App\Models\MonthlyBill;
use App\Models\Tenant;
use App\Models\User;
use App\Services\AutoBillGenerator;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;

uses(RefreshDatabase::class);

// ─── Helper to build a complete flat+tenant setup ────────────────────────
function buildActiveFlat(User $admin, array $flatOverrides = [], ?string $startDate = null): array
{
    $building = Building::create([
        'user_id' => $admin->id,
        'name'    => 'Auto-Bill Test Building',
        'address' => 'Test Address',
    ]);

    $flat = Flat::create(array_merge([
        'building_id'        => $building->id,
        'flat_name'          => 'Flat-AutoTest',
        'status'             => 'occupied',
        'bill_status'        => 'active',
        'house_rent'         => 5000,
        'wasa'               => 200,
        'common_electricity' => 100,
        'gas'                => 150,
        'utility'            => 0,
        'parking'            => 0,
        'society_bill'       => 0,
        'security'           => 0,
        'other'              => 0,
    ], $flatOverrides));

    $tenant = Tenant::create([
        'tenant_id' => 'TNT-TEST-' . uniqid(),
        'name'      => 'Auto Test Tenant',
        'phone'     => '01700000000',
    ]);

    $flatTenant = FlatTenant::create([
        'flat_id'    => $flat->id,
        'tenant_id'  => $tenant->id,
        'start_date' => $startDate ?? now()->subMonth()->toDateString(),
        'status'     => 'active',
    ]);

    return compact('building', 'flat', 'tenant', 'flatTenant');
}

// ─── Test 1: Bills are generated automatically on login ───────────────────
test('auto bill generator creates bill for current month on login', function () {
    $admin = User::factory()->create(['role' => 'admin', 'status' => 'approved']);
    [, $flat] = array_values(buildActiveFlat($admin));

    // No bill should exist yet
    expect(MonthlyBill::where('flat_id', $flat->id)->count())->toBe(0);

    // Run the generator
    AutoBillGenerator::generateForUser($admin->id);

    // Now a bill for the current month should exist
    $currentMonth = now()->format('Y-m');
    $bill = MonthlyBill::where('flat_id', $flat->id)
        ->where('bill_month', $currentMonth)
        ->first();

    expect($bill)->not->toBeNull();
    expect($bill->collection_status)->toBe('due');
    expect($bill->total_amount)->toBe('5450.00'); // 5000+200+100+150
    expect($bill->generated_by)->toBeNull(); // system-generated
    expect($bill->notes)->toBe('Auto-generated by system.');
});

// ─── Test 2: No duplicate bill created if one already exists ──────────────
test('auto bill generator skips if bill for current month already exists', function () {
    $admin = User::factory()->create(['role' => 'admin', 'status' => 'approved']);
    [, $flat, $tenant, $flatTenant] = array_values(buildActiveFlat($admin));

    $currentMonth = now()->format('Y-m');
    [$year, $month] = explode('-', $currentMonth);

    // Manually create a bill for this month
    MonthlyBill::create([
        'flat_id'           => $flat->id,
        'building_id'       => $flat->building_id,
        'tenant_id'         => $tenant->id,
        'flat_tenant_id'    => $flatTenant->id,
        'bill_month'        => $currentMonth,
        'bill_year'         => (int) $year,
        'bill_month_number' => (int) $month,
        'house_rent'        => 5000,
        'wasa'              => 200,
        'common_electricity'=> 100,
        'gas'               => 150,
        'utility'           => 0,
        'parking'           => 0,
        'society_bill'      => 0,
        'security'          => 0,
        'other'             => 0,
        'total_amount'      => 5450,
        'paid_amount'       => 0,
        'remaining_amount'  => 5450,
        'previous_due'      => 0,
        'collection_status' => 'due',
        'generated_by'      => $admin->id,
    ]);

    // Run generator again
    AutoBillGenerator::generateForUser($admin->id);

    // Count should still be 1 — no duplicate
    $count = MonthlyBill::where('flat_id', $flat->id)
        ->where('bill_month', $currentMonth)
        ->count();

    expect($count)->toBe(1);
});

// ─── Test 3: Inactive flat is skipped ────────────────────────────────────
test('auto bill generator skips flats with bill_status inactive', function () {
    $admin = User::factory()->create(['role' => 'admin', 'status' => 'approved']);
    [, $flat] = array_values(buildActiveFlat($admin, ['bill_status' => 'inactive']));

    AutoBillGenerator::generateForUser($admin->id);

    expect(MonthlyBill::where('flat_id', $flat->id)->count())->toBe(0);
});

// ─── Test 4: Vacant flat is skipped ─────────────────────────────────────
test('auto bill generator skips flats with status vacant', function () {
    $admin = User::factory()->create(['role' => 'admin', 'status' => 'approved']);
    [, $flat] = array_values(buildActiveFlat($admin, ['status' => 'vacant']));

    AutoBillGenerator::generateForUser($admin->id);

    expect(MonthlyBill::where('flat_id', $flat->id)->count())->toBe(0);
});

// ─── Test 5: Tenant who started in the future is skipped ──────────────────
test('auto bill generator skips if tenant start_date is in the future', function () {
    $admin = User::factory()->create(['role' => 'admin', 'status' => 'approved']);
    $futureDate = now()->addMonth()->toDateString();
    [, $flat] = array_values(buildActiveFlat($admin, [], $futureDate));

    AutoBillGenerator::generateForUser($admin->id);

    expect(MonthlyBill::where('flat_id', $flat->id)->count())->toBe(0);
});

// ─── Test 6: Previous due is carried over from last bill ──────────────────
test('auto bill generator carries over previous_due from last unpaid bill', function () {
    $admin = User::factory()->create(['role' => 'admin', 'status' => 'approved']);
    [, $flat, $tenant, $flatTenant] = array_values(buildActiveFlat($admin));

    $lastMonth = now()->subMonth()->format('Y-m');
    [$ly, $lm] = explode('-', $lastMonth);

    // Create a previous unpaid bill with remaining_amount
    MonthlyBill::create([
        'flat_id'           => $flat->id,
        'building_id'       => $flat->building_id,
        'tenant_id'         => $tenant->id,
        'flat_tenant_id'    => $flatTenant->id,
        'bill_month'        => $lastMonth,
        'bill_year'         => (int) $ly,
        'bill_month_number' => (int) $lm,
        'house_rent'        => 5000,
        'wasa'              => 0, 'common_electricity' => 0, 'gas' => 0,
        'utility' => 0, 'parking' => 0, 'society_bill' => 0, 'security' => 0, 'other' => 0,
        'total_amount'      => 5000,
        'paid_amount'       => 2000,
        'remaining_amount'  => 3000, // ← 3000 BDT remaining
        'previous_due'      => 0,
        'collection_status' => 'partial',
        'generated_by'      => $admin->id,
    ]);

    AutoBillGenerator::generateForUser($admin->id);

    $currentMonth = now()->format('Y-m');
    $newBill = MonthlyBill::where('flat_id', $flat->id)
        ->where('bill_month', $currentMonth)
        ->first();

    expect($newBill)->not->toBeNull();
    expect((float) $newBill->previous_due)->toBe(3000.0);
    // remaining = total(5450) + previous_due(3000) = 8450
    expect((float) $newBill->remaining_amount)->toBe(8450.0);
});
